name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew assembleDebug

      - uses: actions/upload-artifact@v3
        with:
          name: SMSAdBlocker
          path: ./app/build/outputs/apk/release/app-release-unsigned.apk

      - name: Release
        uses: fnkr/github-action-ghr@v1
        env:
          GHR_PATH: ./app/build/outputs/apk/release/app-release-unsigned.apk
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
