name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: sparkfabrik/android-build-action@v1.0.0
      with:
        project-path: /home/runner/work/SMS_Ad_Blocker/
        output-path: SMS_Ad_Blocker_release.apk
        gradle-task: assembleRelease
   
